### ISSUE TITLE
CWE-200: Exposure of Sensitive Information to an Unauthorized Actor (x-powered-by) (Team 4) (Medium)

### ISSUE THREAD

**Issue by MagicianMido32** [ELG7186-s22/project-group-2#12]
this header reveals the type and version of your server to the attacker.
Go to your app.js and just after:
var app = express();
Add:
app.disable('x-powered-by');

**Comment by AhmedYHamza** [comment]
Thank you for bringing this issue to our attention. We will try to solve it promptly once we verify it.

**Comment by AhmedYHamza** [comment]
The code didn't have an app.js file. But, we found this issue in our server.js, so, thanks a ton for your pointing out of this issue.
