### ISSUE TITLE
Missing/incorrect Authorization && Reliance on Untrusted Inputs (team 4)

### ISSUE THREAD

**Issue by atia98** [ELG7186-s22/project-group-2#14]
![WhatsApp Image 2022-08-05 at 3 34 29 AM](https://user-images.githubusercontent.com/57109699/182983187-c62da1eb-8d32-4846-83ce-503b1c82a312.jpeg)

a malicious can unauthorized access to instructor page and control on challenge solution access

**Comment by AhmedYHamza** [comment]
Thank you for your feedback. This issue has already been posted prior. We appreciate your support.
