### ISSUE TITLE
 CWE-552: Files or Directories Accessible to External Parties(team4) (Critical) 

### ISSUE THREAD

**Issue by atia98** [ELG7186-s22/project-group-2#15]
a student can access challenges solution even though he or she is prevented
example:
I can know all information about challenges from unauthorized browsing for
by knowing the challenge id i can unauthorized access the challenge html page and download the file.sol.md 
![Screenshot from 2022-08-05 03-55-17](https://user-images.githubusercontent.com/57109699/182985477-0db0a945-ed1d-4188-9198-53e670c9efd6.png)
![Screenshot from 2022-08-05 03-59-15](https://user-images.githubusercontent.com/57109699/182985486-409562a9-620a-41cd-8029-d94eb37c9e63.png)

**Comment by AhmedYHamza** [comment]
Thank you for your feedback. This issue has already been posted prior. We appreciate your support.
