### ISSUE TITLE
ERROR: Config file not found. [High Priority bug] (Team 3)

### ISSUE THREAD

**Issue by OmniaSolimanMohamed** [ELG7186-s22/project-group-2#7]
**ERROR: Config file not found.**
can you please push the config file so we can run the project, according to the TA.

**Comment by AhmedYHamza** [comment]
Actually this isn't a bug at all. If you refer to the documentation of this project, you will find specific instructions to deploy this project in development mode, including but not limited to building your own config json drawing on the blueprint found in the files called config json sample. Furthermore, if you need a config to get you started there is one ready in the build folder of the project. However, if you want our own copy of the config json, please provide us some more details on why you need it and we will be happy to help.

**Comment by norantharowat** [comment]
Good to know that the config file is still the same as the one provided in the build folder, thank you we will use that.
