### ISSUE TITLE
unauthorized redirect (Team 3) 

### ISSUE THREAD

**Issue by OmniaSolimanMohamed** [ELG7186-s22/project-group-2#8]
when trying to access unauthorized page from student account (instructor.html) we were able to access it, we know that it' an empty combo box but you disclosed the structure of unauthorized page to unauthorized user.
![image](https://user-images.githubusercontent.com/47222715/182208194-0267ed87-68e0-454a-870e-6d5fda4a1fee.png)

**Comment by AhmedYHamza** [comment]
It seems like this particular issue is haunting all the groups for some reason. We tried to secure all the end-points, but this one seems to have escaped us. We will try to solve this issue promptly. Thank you for bringing this to our attention.

**Comment by AhmedYHamza** [comment]
Thank you for pointing out this issue, I am happy to announce that it is fixed now.
![Screenshot 2022-08-08 225000](https://user-images.githubusercontent.com/66231209/183512513-62d2c37a-64f0-4122-8e86-9cb8f708d2a6.jpg)
![Screenshot 2022-08-08 225037](https://user-images.githubusercontent.com/66231209/183512515-0da80036-8809-4a67-84c1-3eb97d671327.jpg)
