### ISSUE TITLE
Misleading user feedback (Team 3)

### ISSUE THREAD

**Issue by norantharowat** [ELG7186-s22/project-group-2#9]
In all cases, when the admin tries to edit the hide/show solution, the system will tell the admin that his input is saved, even if the request  failed.
you should check first if the request returns success, then log saved to the admin.

Also, you do not send any response from the /instructorsetting route in the server, either success or failure, so the .then() chain is never entered in the first place.
If an error happens in the backend the user will be prompted the saved alert, without knowing that his request failed.
  
![image](https://user-images.githubusercontent.com/43759597/182219086-049f4f78-bc9d-454a-85d2-c6d0d976b962.png)

**Comment by AhmedYHamza** [comment]
You are absolutely right, thank you for bringing this issue to our attention.

**Comment by AhmedYHamza** [comment]
Just letting you that this issue is now fixed.
